global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    scrape_interval: 5s
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: agent_amount
    scrape_interval: 5s
    static_configs:
      - targets: ["agent_amount:8001"]

  - job_name: agent_frequency
    scrape_interval: 5s
    static_configs:
      - targets: ["agent_frequency:8002"]

  - job_name: agent_geolocation
    scrape_interval: 5s
    static_configs:
      - targets: ["agent_geolocation:8003"]

  - job_name: agent_device
    scrape_interval: 5s
    static_configs:
      - targets: ["agent_device:8004"]

  - job_name: aggregator
    scrape_interval: 5s
    static_configs:
      - targets: ["aggregator:8005"]